### PR TITLE
extracting text from scanned pdfs

### PR DESCRIPTION
**Pull request by kirk86**
Approach for extracting/ocr text from scanned pdfs.

### CODE REVIEW

**Comment by perrette** [comment]
right, we just need the dependencies now ; )

**Comment by perrette** [comment]
hmm, why is it failing? 
`FileNotFoundError: [Errno 2] No such file or directory: 'tesseract'`

**Comment by kirk86** [comment]
Where can I see the failure you're referring to? In the [travis ci](https://travis-ci.org/perrette/papers/pull_requests) I can see that PR #82 failed which was the one without the dependencies but I can't seem find anything about the last PR with dependencies in failed build history.

**Comment by perrette** [comment]
That was just Travis CI lagging behind. All good.

2019-06-01 0:21 UTC+02:00, kirk86 <notifications@github.com>:

**Comment by perrette** [comment]
No in fact there was an error in .travis.yml , so it could not be parsed.
Then the code was not working in python 2.7
I rewrote the readpdf function in a clear manner, but now I am also faced with the 'hyphen' bug you were mentioning. Have you figured that one out?

**Comment by perrette** [comment]
This makes me think that image recognition is less reliable than pure pdf to text.
My thinking now is that the default should be pdf to text, while pdf to image to text should be an option for old papers.

**Comment by perrette** [comment]
Right, so I rolled back to pdftotext extraction for now, until the failure is figured out. 
My guess is that an older version of tesseract on travis may be responsible. 
There is now a readpdf_image function that does the tesseract thing. It is not integrated with the command line yet. This can be done later. I just cannot spend more time on this now.

**Comment by perrette** [comment]
(what's more: using tesseract comes with nasty unicode issues in python 2.7 version on travis)

**Pull request merged**
